In [2]:
import geopandas
import json
import numpy as np
import pandas as pd

import math

In [3]:
mk_municipalities = geopandas.read_file("../local/mk_municipalities/mk_municipalities.geojson")
mk_cities = mk_municipalities.dissolve(by='entity_mk', aggfunc='sum')                                
# mk_cities['entity_mk'] = mk_cities.index
mk_cities['id'] = mk_cities.index
mk_cities

,geometry,latitude,longitude,area_sqkm,area,population,scalerank,diss_me,adm0_sr,provnum_ne,...,adm0_label,gn_id,gns_id,gn_level,gns_level,min_label,max_label,min_zoom,ne_id,id
entity_mk,,,,,,,,,,,,,,,,,,,,,
Јегуновце,"POLYGON ((21.02797 42.02765, 21.02810 42.02753...",42.0311,21.1290,0,174.0,10.790,10,2963,1,20001,...,5,863858,9075623,1,1,10.0,11.0,10.0,1159314547,Јегуновце
Арачиново,"POLYGON ((21.61108 42.08140, 21.61101 42.08098...",42.0185,21.5862,0,38.0,11.597,10,2919,1,20057,...,5,863831,9075577,1,1,10.0,11.0,10.0,1159314449,Арачиново
Берово,"POLYGON ((22.78298 41.78510, 22.78360 41.78545...",41.6344,22.8027,0,597.0,13.941,10,3004,1,20029,...,5,863485,9058335,1,1,10.0,11.0,10.0,1159314569,Берово
Битола,"POLYGON ((21.25219 40.89330, 21.24280 40.87920...",41.0402,21.2925,0,790.0,95.385,10,2896,1,20040,...,5,863486,9058342,1,1,10.0,11.0,10.0,1159314401,Битола
Богданци,"POLYGON ((22.52113 41.15881, 22.52180 41.15898...",41.1772,22.5841,0,114.0,8.707,10,2996,1,20025,...,5,862950,9043540,1,1,10.0,11.0,10.0,1159314555,Богданци
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Центар Жупа,"POLYGON ((20.66262 41.44884, 20.66553 41.44795...",41.4644,20.5799,0,107.0,6.519,10,2951,1,20036,...,5,863841,9075602,1,1,10.0,11.0,10.0,1159314519,Центар Жупа
Чашка,"POLYGON ((21.81383 41.49223, 21.81417 41.49180...",41.5807,21.5939,0,727.0,7.673,10,2922,1,20070,...,5,863838,9075596,1,1,10.0,11.0,10.0,1159314457,Чашка
Чешиново-Облешево,"POLYGON ((22.21717 41.85944, 22.21745 41.85988...",41.8644,22.2896,0,133.0,7.490,10,2925,1,20058,...,5,862977,9043609,1,1,10.0,11.0,10.0,1159314463,Чешиново-Облешево
Чучер Сандево,"POLYGON ((21.52347 42.19750, 21.52344 42.19761...",42.1353,21.3885,0,215.0,8.493,10,2926,1,20004,...,5,863842,9075604,1,1,10.0,11.0,10.0,1159314465,Чучер Сандево
Штип,"POLYGON ((22.41569 41.72909, 22.41546 41.72934...",41.6824,22.1689,0,583.0,47.796,10,2911,1,20046,...,5,863900,9075766,1,1,10.0,11.0,10.0,1159314431,Штип

In [5]:
quarantine_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vR-Ul4NMiPvca7QH-RlYk2Q1hrVmjjGp5tr5n64l1z-SH5S2NoMeqjSd5Ulo171tHKM2Crfr7u0tpcz/pub?gid=325857359&single=true&output=csv")
quarantine_df

       Општина    Од датум  До датум
0        Дебар  2020-03-12       NaN
1  Центар Жупа  2020-03-12       NaN

In [7]:
mk_cities_quarantine = mk_cities.merge(quarantine_df, left_on='entity_mk', right_on='Општина', how='inner')

In [12]:
mk_cities_quarantine['dissolvefield'] = 1
quarantine = mk_cities_quarantine.dissolve(by='dissolvefield', aggfunc='sum')
quarantine

,geometry,latitude,longitude,area_sqkm,area,population,scalerank,diss_me,adm0_sr,provnum_ne,...,adm0_label,gn_id,gns_id,gn_level,gns_level,min_label,max_label,min_zoom,ne_id,До датум
dissolvefield,,,,,,,,,,,,,,,,,,,,,
1,"POLYGON ((20.68236 41.43111, 20.68161 41.43045...",83.0054,41.1662,0,192.0,26.061,20,5903,2,40071,...,10,1727684,18151207,2,2,20.0,22.0,20.0,2318629040,0.0

In [16]:
quarantine[['geometry', 'population']].to_file("../podatoci/macedonia/covid-quarantine.geojson", 'GeoJSON')

In [17]:
quarantine

,geometry,latitude,longitude,area_sqkm,area,population,scalerank,diss_me,adm0_sr,provnum_ne,...,adm0_label,gn_id,gns_id,gn_level,gns_level,min_label,max_label,min_zoom,ne_id,До датум
dissolvefield,,,,,,,,,,,,,,,,,,,,,
1,"POLYGON ((20.68236 41.43111, 20.68161 41.43045...",83.0054,41.1662,0,192.0,26.061,20,5903,2,40071,...,10,1727684,18151207,2,2,20.0,22.0,20.0,2318629040,0.0